config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'messages/loader' => 'messages#loader'
  get 'home/letrock' => 'home#letrock'

  resources :profiles, only:[:index,:show,:edit,:update]
  resources :messages
  resources :orders
  resources :locations, only:[:index,:new,:create,:edit,:update]
  resources :books, only:[:index,:new,:create,:edit,:update]
  resources :inventories
  root to:'home#index'
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!
  # <Message id: nil, title: nil, body: nil, view: nil, user_id: nil, created_at: nil, updated_at: nil>

  def loader
    @mes = Message.where(user_id:current_user.id).last(4)
  end

  def index
    if current_user.typo == "worker"
      @pagy, @item = pagy_array(Message.all)
      @user = [User.find(@item.map { |f| f.user_id })]
    else
      @pagy, @item = pagy_array(Message.where(user_id:current_user.id))
      @user = [User.find(@item.map { |f| f.user_id })]
    end

  end

  def new
    @gente = User.all
  end

  def create
    ret = false
    m = Message.new
    m.title = params["title"]
    m.body = params["text"]
    m.view = params["status"]
    m.user_id = params["user_id"]
    ret = m.save
    if ret
      flash["success"] ="mensage creada"
      redirect_to controller:'messages', action: "index"
    else
      flash["danger"] ="error al crear"
      redirect_back(fallback_location: root_path)
    end
  end

  # of the class
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_showi.html.erb
<div id="product-modal" class="modal fade">
  <div class="modal-dialog ">
    <div class="modal-content">
      <div class="modal-header  bg-success text-white">
        <h4 class="modal-title">Mensajes</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      </div>
      <div class="modal-body">
        <% if @mes.present? %>
        <p><b>Listado de mensajes:</b></p>
          <% @mes.each do |item| %>
        <ul>
          <li><span class=" text-white bg-<%= mesage_color(item.view) %>"><b>AVISO:</b> <%= mesage_satus( item.view) %></span></li>
          <li><b>Titulo:</b> <%= item.title %></li>
          <li><b>Mensaje:</b> <%= item.body %></li>
          <li><b>Fecha:</b> <%= date_format(item.updated_at) %></li>

        </ul>
        <% end %>
        <hr>
        <% else %>
        <p><b>Listado de mensajes:</b></p>
        <h2>no tiene mensajes actualmente</h2>
        <% end %>
      </div>
      <div class="modal-footer">
          <% if @mes.present? %>
          <%= link_to "todos",messages_path, class:"btn-btn-info" %>
          <% end %>
        <button type="button" class="btn btn-outline-dark" data-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>

app/views/messages/edit.html.erb
<div id="wrapper">
  <%= render 'shared/sidebar'%>

  <div id="content-wrapper" class="d-flex flex-column">
    <div id="content">
      <%= render 'shared/topbar' %>
      <div class="container-fluid">
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
          <h1 class="h3 mb-0 text-gray-800">Ordenes</h1>
        </div>
        <div class="card shadow">
          <div class="card-header">
            Nueva Mensaje
          </div>
          <div class="card-body">
            <%if @gente.present? %>
            <%= form_tag( messages_path, action:"create", method: "post", id: "updateForm", multipart: true) do %>
            <div class="row">
              <div class="col-md-6">
                <div class="form-group row">
                  <label class="col-sm-3 col-form-label">Cliente</label>
                  <div class="col-sm-9">
                    <%= select_tag :user_id, options_from_collection_for_select(@gente,:id, :email), class:'form-control', include_blank: true %>
                  </div>
                </div>
              </div>
              <div class="col-md-6">
                <div class="form-group row">
                  <label class="col-sm-3 col-form-label">Estado:</label>
                  <div class="col-sm-9">
                    <%= select_tag :status, options_for_select($order_status), class:'form-control', include_blank: true %>
                  </div>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-md-6">
                <div class="form-group row">
                  <label class="col-sm-3 col-form-label">Titulo:</label>
                  <div class="col-sm-9">
                    <%= text_field_tag :title , '', placeholder:"" , class:'form-control' %>
                  </div>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-md-6">
                <div class="form-group row">
                  <label class="col-sm-3 col-form-label">descripción</label>
                  <div class="col-sm-9">
                    <%= text_area_tag :texto , '' , placeholder:"", class:'form-control' %>
                  </div>
                </div>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-md-4">
                <div class="form-group row">
                  <div class="col">
                    <%= submit_tag 'Guardar', class:'btn btn-success' %>
                  </div>
                  <div class="col">
                    <%= link_to 'volver', orders_path , class:'btn btn-light' %>
                  </div>
                </div>
              </div>
            </div>

            <% end %>
            <% else %>
            <%= link_to 'volver', orders_path , class:'btn btn-light' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>

    <%= render 'shared/footer' %>
  </div>
</div>

app/views/messages/index.html.erb
<div id="wrapper">
  <%= render 'shared/sidebar'%>
  <div id="content-wrapper" class="d-flex flex-column">
    <div id="content">
      <%= render 'shared/topbar' %>
      <div class="container-fluid">
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
          <h1 class="h3 mb-0 text-gray-800">Ordenes</h1>
        </div>
        <div class="card shadow">
          <div class="card-header">
            tienda libros
          </div>
          <div class="card-body">
            <h2> ubiaciones</h2>
            <%if @item.present? %>
            <table class="table table-sm">
              <thead>
                <tr>
                  <th>id</th>
                  <th>aviso:</th>
                  <th>titulo</th>
                  <th>usuario</th>
                  <th>fecha</th>
                  <th>revisar</th>
                </tr>
              </thead>
              <tbody>
                <% @item.as_json.each do |line|%>
                <tr>
                  <td><%= line["id"] %></td>
                  <td class=" text-white bg-<%= mesage_color(line["view"]) %>"> <%= mesage_satus( line["view"]) %></td>
                  <td><%= line["title"] %></td>
                  <td><%= line["user_id"] %>: <%= @user.find(line["user_id"]).first.first.email if line["user_id"].present? && @user.present? %></td>
                  <td><%=date_format(line["updated_at"]) %></td>
                  <td><%= link_to edit_message_path(id:line["id"]) do %><i class="fas fa-comment-dots"></i><% end %></td>
                </tr>
                <% end %>
              </tbody>
            </table>
            <% else %>
            <p>no hay locaciones</p>
            <% end %>
            <hr>
            <%= link_to 'nueva', new_location_path , class:"btn btn-info" %>
          </div>
        </div>
      </div>
    </div>
    <%= render 'shared/footer' %>
  </div>
</div>

app/views/messages/loader.js.erb
$('<%= j render "showi", title: "Mensajes", data:@mes %>').modal();

app/views/messages/new.html.erb
<div id="wrapper">
  <%= render 'shared/sidebar'%>

  <div id="content-wrapper" class="d-flex flex-column">
    <div id="content">
      <%= render 'shared/topbar' %>
      <div class="container-fluid">
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
          <h1 class="h3 mb-0 text-gray-800">Ordenes</h1>
        </div>
        <div class="card shadow">
          <div class="card-header">
            Nueva Mensaje
          </div>
          <div class="card-body">
            <%if @gente.present? %>
            <%= form_tag( message_path, action:"create", method: "post", id: "updateForm", multipart: true) do %>
            <div class="row">
              <div class="col-md-6">
                <div class="form-group row">
                  <label class="col-sm-3 col-form-label">Cliente</label>
                  <div class="col-sm-9">
                    <%= select_tag :user_id, options_from_collection_for_select(@gente,:id, :email), class:'form-control', include_blank: true %>
                  </div>
                </div>
              </div>
              <div class="col-md-6">
                <div class="form-group row">
                  <label class="col-sm-3 col-form-label">Estado:</label>
                  <div class="col-sm-9">
                    <%= select_tag :location, options_for_select($order_status), class:'form-control', include_blank: true %>
                  </div>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-md-6">
                <div class="form-group row">
                  <label class="col-sm-3 col-form-label">Titulo:</label>
                  <div class="col-sm-9">
                    <%= text_field_tag :title , '', placeholder:"" , class:'form-control' %>
                  </div>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-md-6">
                <div class="form-group row">
                  <label class="col-sm-3 col-form-label">descripción</label>
                  <div class="col-sm-9">
                    <%= text_area_tag :table , '' , placeholder:"", class:'form-control' %>
                  </div>
                </div>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-md-4">
                <div class="form-group row">
                  <div class="col">
                    <%= submit_tag 'Guardar', class:'btn btn-success' %>
                  </div>
                  <div class="col">
                    <%= link_to 'volver', orders_path , class:'btn btn-light' %>
                  </div>
                </div>
              </div>
            </div>

            <% end %>
            <% else %>
            <%= link_to 'volver', orders_path , class:'btn btn-light' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>

    <%= render 'shared/footer' %>
  </div>
</div>