config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'messages/loader' => 'messages#loader'
  get 'home/letrock' => 'home#letrock'

  resources :profiles, only:[:index,:show,:edit,:update]
  resources :messages
  resources :orders
  resources :locations, only:[:index,:new,:create,:edit,:update]
  resources :books, only:[:index,:new,:create,:edit,:update]
  resources :inventories
  root to:'home#index'
end

app/views/shared/_footer.html.erb
<footer class="sticky-footer bg-white">
  <div class="container my-auto">
    <div class="copyright text-center my-auto">
      <span>Copyright &copy; Duoc 2020 </span>
    </div>
  </div>
</footer>

app/views/shared/_sidebar.html.erb
<!-- Sidebar -->
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
  <!-- Sidebar - Brand -->
  <a class="sidebar-brand d-flex align-items-center justify-content-center" href="#">
    <div class="sidebar-brand-icon rotate-n-15">
      <i class="fas fa-book"></i>
      <i class="fas fa-book-open text-warning"></i>
    </div>
    <div class="sidebar-brand-text mx-3">Ventabook</div>
  </a>

  <!-- Divider -->
  <hr class="sidebar-divider my-0">

  <li class="nav-item">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
    <i class="fas fa-file-invoice"></i>
      <span>Ordenes</span>
    </a>
    <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
      <div class="bg-white py-2 collapse-inner rounded">
        <%= link_to 'Listado Ordenes', orders_path, class:"collapse-item" %>
        <%= link_to 'nueva orden', new_order_path, class:"collapse-item" %>
      </div>
    </div>
  </li>
  <li class="nav-item">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTree" aria-expanded="true" aria-controls="collapseTwo">
      <i class="fas fa-comment-dots"></i>
      <span>Notificaciones</span>
    </a>
    <div id="collapseTree" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
      <div class="bg-white py-2 collapse-inner rounded">
        <%= link_to 'Mis mensajes',  messages_loader_path, class:"collapse-item" , remote: true %>
        <%= link_to 'todos los mensajes', messages_path, class:"collapse-item" %>
        <%if user_signed_in?  && current_user.typo == "worker"%>
        <%= link_to 'nuevo mensajes', new_message_path, class:"collapse-item" %>
        <% end %>
      </div>
    </div>
  </li>
  <!-- Divider -->
  <hr class="sidebar-divider d-none d-md-block">
  <%if user_signed_in?  && current_user.typo == "worker"%>
  <li class="nav-item">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseIII" aria-expanded="true" aria-controls="collapseIII">
      <i class="fas fa-store"></i>
      <span>Ubicaciones</span>
    </a>
    <div id="collapseIII" class="collapse" aria-labelledby="headingIII" data-parent="#accordionSidebar">
      <div class="bg-white py-2 collapse-inner rounded">
        <%= link_to 'listado', locations_path, class:"collapse-item" %>
        <%= link_to 'nueva ', new_location_path, class:"collapse-item" %>
      </div>
    </div>
  </li>
  <li class="nav-item">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseIV" aria-expanded="true" aria-controls="collapseIV">
      <i class="fas fa-book"></i>
      <span>Libros</span>
    </a>
    <div id="collapseIV" class="collapse" aria-labelledby="headingIV" data-parent="#accordionSidebar">
      <div class="bg-white py-2 collapse-inner rounded">
        <%= link_to 'listado', books_path, class:"collapse-item" %>
        <%= link_to 'nuevo ', new_book_path, class:"collapse-item" %>
      </div>
    </div>
  </li>
  <li class="nav-item">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseV" aria-expanded="true" aria-controls="collapseV">
      <i class="fas fa-box-open"></i>
      <span>Inventario</span>
    </a>
    <div id="collapseV" class="collapse" aria-labelledby="headingV" data-parent="#accordionSidebar">
      <div class="bg-white py-2 collapse-inner rounded">
        <%= link_to 'Actual', inventories_path, class:"collapse-item" %>
        <%= link_to 'ingresar ', new_inventory_path, class:"collapse-item" %>
      </div>
    </div>
  </li>
  <hr class="sidebar-divider d-none d-md-block">
  <% end %>
</ul>
<!-- End of Sidebar -->

app/views/shared/_topbar.html.erb
<!-- Topbar -->
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

  <!-- Sidebar Toggle (Topbar) -->
  <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
    <i class="fa fa-bars"></i>
  </button>


<!-- Topbar Navbar -->
<ul class="navbar-nav ml-auto">
  <%flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %> alert-dismissible">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    <%= message %>
  </div>
  <% end %>

  <div class="topbar-divider d-none d-sm-block"></div>

  <!-- Nav Item - User Information -->
  <li class="nav-item dropdown no-arrow">
    <%if user_signed_in? %>
    <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <span class="mr-2 d-none d-lg-inline text-gray-600 small"><%= current_user.email %></span>
      <%= icon('fas','user')%>
    </a>
    <!-- Dropdown - User Information -->
    <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
          <%= link_to  profile_path(:id => current_user.id), class:"dropdown-item"  do %>
        <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
        Perfil
        <% end %>
      <% if current_user.id == 1 %>
      <%= link_to  profiles_path, class:"dropdown-item"  do %>
        <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
        Administrar usuarios
      <% end %>
      <% end %>
      <div class="dropdown-divider"></div>
      <%= link_to  destroy_user_session_path , class:"dropdown-item", method:"delete" do %>
        <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
        Logout
      <% end %>
    </div>
    <% else %>
    <%= link_to  new_user_session_path, class:"nav-link"  do %>
      <span class="mr-2 d-none d-lg-inline text-gray-600 small">Iniciar sesión</span>
      <%= icon('fas','sign-in-alt')%>
    <% end %>
    <% end %>
  </li>

</ul>

</nav>
<!-- End of Topbar -->