config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'messages/loader' => 'messages#loader'
  get 'home/letrock' => 'home#letrock'

  resources :profiles, only:[:index,:show,:edit,:update]
  resources :messages
  resources :orders
  resources :locations, only:[:index,:new,:create,:edit,:update]
  resources :books, only:[:index,:new,:create,:edit,:update]
  resources :inventories
  root to:'home#index'
end

app/models/book.rb
class Book < ApplicationRecord
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  # Book id: nil, name: nil, value: nil, created_at: nil, updated_at: nil
  def index
    @item = Book.all
  end

  def new
    @item = Book.new
  end

  def edit
    @item = Book.find(params[:id])
    redirect_to controller:'books', action: "index" if @item.blank
  end

  def create
    b = Book.new
    b.name = params[:name]
    b.value = params[:value]
    ret = b.save
    if ret
      flash["success"] ="libro  creado"
      redirect_to controller:'books', action: "index"
    else
      flash["danger"] ="error al crear"
      redirect_back(fallback_location: root_path)
    end
  end

  def update
    b = Book.find(params[:id])
    redirect_back(fallback_location: root_path) if b.blank?
    b.name = params[:name]
    b.value = params[:value]
    ret = b.save
    if ret
      flash["success"] ="libro  creado"
      redirect_to controller:'books', action: "index"
    else
      flash["danger"] ="error al crear"
      redirect_back(fallback_location: root_path)
    end
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<div id="wrapper">
  <%= render 'shared/sidebar'%>
  <div id="content-wrapper" class="d-flex flex-column">
    <div id="content">
      <%= render 'shared/topbar' %>
      <div class="container-fluid">
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
          <h1 class="h3 mb-0 text-gray-800">Ordenes</h1>
        </div>
        <div class="card shadow">
          <div class="card-header">
            tienda libros
          </div>
          <div class="card-body">
            <h2> actualizar libro</h2>
            <%= form_tag( book_path, action:"update", method: "put", id: "updateForm", multipart: true) do %>
            <label class="">nombre:</label>
            <%= text_field_tag :name ,@item.name, placeholder:"" , class:'form-control' %>
            <label class="">valor:</label>
            <%= number_field_tag :value , @item.value, placeholder:"" , class:'form-control' %>
            <hr>
            <%= submit_tag 'Guardar', class:'btn btn-success' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <%= render 'shared/footer' %>
  </div>
</div>

app/views/books/index.html.erb
<div id="wrapper">
  <%= render 'shared/sidebar'%>
  <div id="content-wrapper" class="d-flex flex-column">
    <div id="content">
      <%= render 'shared/topbar' %>
      <div class="container-fluid">
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
          <h1 class="h3 mb-0 text-gray-800">Ordenes</h1>
        </div>
        <div class="card shadow">
          <div class="card-header">
            tienda libros
          </div>
          <div class="card-body">
            <h2> libros</h2>
            <%if @item.present? %>
            <table class="table table-sm">
              <thead>
                <tr>
                  <th>id</th>
                  <th>libro</th>
                  <th>valor</th>
                  <th>fecha</th>
                  <th>revisar</th>
                </tr>
              </thead>
              <tbody>
                <% @item.as_json.each do |line|%>
                <tr>
                  <td><%= line["id"] %></td>
                  <td><%= line["name"] %></td>
                  <td><%= line["value"] %></td>
                  <td><%=date_format(line["updated_at"]) %></td>
                  <td><%= link_to edit_book_path(id:line["id"]) do %><i class="fas fa-book"></i><% end %></td>
                </tr>
                <% end %>
              </tbody>
            </table>
            <% else %>
            <p>no hay locaciones</p>
            <% end %>
            <hr>
            <%= link_to 'nueva', new_book_path , class:"btn btn-info" %>
          </div>
        </div>
      </div>
    </div>
    <%= render 'shared/footer' %>
  </div>
</div>

app/views/books/new.html.erb
<div id="wrapper">
  <%= render 'shared/sidebar'%>
  <div id="content-wrapper" class="d-flex flex-column">
    <div id="content">
      <%= render 'shared/topbar' %>
      <div class="container-fluid">
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
          <h1 class="h3 mb-0 text-gray-800">Ordenes</h1>
        </div>
        <div class="card shadow">
          <div class="card-header">
            tienda libros
          </div>
          <div class="card-body">
            <h2> nuevo libro</h2>
            <%= form_tag( books_path, action:"create", method: "post", id: "updateForm", multipart: true) do %>
            <label class="">nombre:</label>
            <%= text_field_tag :name , '', placeholder:"" , class:'form-control' %>
            <label class="">valor:</label>
            <%= number_field_tag :value , '', placeholder:"" , class:'form-control' %>
            <hr>
            <%= submit_tag 'Guardar', class:'btn btn-success' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <%= render 'shared/footer' %>
  </div>
</div>