config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'messages/loader' => 'messages#loader'
  get 'home/letrock' => 'home#letrock'

  resources :profiles, only:[:index,:show,:edit,:update]
  resources :messages
  resources :orders
  resources :locations, only:[:index,:new,:create,:edit,:update]
  resources :books, only:[:index,:new,:create,:edit,:update]
  resources :inventories
  root to:'home#index'
end

app/models/location.rb
class Location < ApplicationRecord
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

 def index
   @item = Location.all
 end

def new
  @item = Location.new
end

def edit
    @item = Location.find(params["id"])
    redirect_to controller:'locations', action: "index" if @item.blank?
end

def create
  l = Location.new
  l.name = params[:name]
  l.stret = params[:stret]
  ret = l.save
  if ret
    flash["success"] ="locaciones creada"
    redirect_to controller:'locations', action: "index"
  else
    flash["danger"] ="error al crear"
    redirect_back(fallback_location: root_path)
  end
end

def update
  l = Location.find(params["id"])
  redirect_back(fallback_location: root_path) if l.blank?
  l.name = params[:name]
  l.stret = params[:stret]
  ret = l.save
  if ret
    flash["success"] ="locacion actualizada"
    redirect_to controller:'locations', action: "index"
  else
    flash["danger"] ="error al crear"
    redirect_back(fallback_location: root_path)
  end
end

end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/edit.html.erb
<div id="wrapper">
  <%= render 'shared/sidebar'%>
  <div id="content-wrapper" class="d-flex flex-column">
    <div id="content">
      <%= render 'shared/topbar' %>
      <div class="container-fluid">
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
          <h1 class="h3 mb-0 text-gray-800">Ordenes</h1>
        </div>
        <div class="card shadow">
          <div class="card-header">
            tienda libros
          </div>
          <div class="card-body">
            <h2> actualizar ubiaciones</h2>
            <%= form_tag( location_path, action:"update", method: "put", id: "updateForm") do %>
            <label class="">nombre:</label>
            <%= text_field_tag :name , @item.name, placeholder:"" , class:'form-control' %>
            <label class="">calle:</label>
            <%= text_field_tag :stret ,@item.stret, placeholder:"" , class:'form-control' %>
            <hr>
            <%= hidden_field_tag "id" , params["id"] %>
            <%= submit_tag 'Guardar', class:'btn btn-success' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <%= render 'shared/footer' %>
  </div>
</div>

app/views/locations/index.html.erb
<div id="wrapper">
  <%= render 'shared/sidebar'%>
  <div id="content-wrapper" class="d-flex flex-column">
    <div id="content">
      <%= render 'shared/topbar' %>
      <div class="container-fluid">
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
          <h1 class="h3 mb-0 text-gray-800">Ordenes</h1>
        </div>
        <div class="card shadow">
          <div class="card-header">
            tienda libros
          </div>
          <div class="card-body">
            <h2> ubiaciones</h2>
            <%if @item.present? %>
            <table class="table table-sm">
              <thead>
                <tr>
                  <th>id</th>
                  <th>nombre</th>
                  <th>calle</th>
                  <th>fecha</th>
                  <th>revisar</th>
                </tr>
              </thead>
              <tbody>
                <% @item.as_json.each do |line|%>
                <tr>
                  <td><%= line["id"] %></td>
                  <td><%= line["name"] %></td>
                  <td><%= line["stret"] %></td>
                  <td><%=date_format(line["updated_at"]) %></td>
                  <td><%= link_to edit_location_path(id:line["id"]) do %><i class="fas fa-store"></i><% end %></td>
                </tr>
                <% end %>
              </tbody>
            </table>
            <% else %>
            <p>no hay locaciones</p>
            <% end %>
            <hr>
            <%= link_to 'nueva', new_location_path , class:"btn btn-info" %>
          </div>
        </div>
      </div>
    </div>
    <%= render 'shared/footer' %>
  </div>
</div>

app/views/locations/new.html.erb
<div id="wrapper">
  <%= render 'shared/sidebar'%>
  <div id="content-wrapper" class="d-flex flex-column">
    <div id="content">
      <%= render 'shared/topbar' %>
      <div class="container-fluid">
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
          <h1 class="h3 mb-0 text-gray-800">Ordenes</h1>
        </div>
        <div class="card shadow">
          <div class="card-header">
            tienda libros
          </div>
          <div class="card-body">
            <h2> nueva ubiaciones</h2>
                <%= form_tag( locations_path, action:"create", method: "post", id: "updateForm", multipart: true) do %>
                  <label class="">nombre:</label>
                  <%= text_field_tag :name , '', placeholder:"" , class:'form-control' %>
                  <label class="">calle:</label>
                  <%= text_field_tag :stret , '', placeholder:"" , class:'form-control' %>
                    <hr>
                      <%= submit_tag 'Guardar', class:'btn btn-success' %>
                <% end %>
          </div>
        </div>
      </div>
    </div>
    <%= render 'shared/footer' %>
  </div>
</div>